version: "3.9"

services:
  traefik:
    image: traefik:latest    
    container_name: traefik
    command:      
      - --log.level=DEBUG
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=$CF_API_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=$DOMAINNAME
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAINNAME
      
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      
    volumes:
      - "/run/user/$PGID/docker.sock:/var/run/docker.sock:ro"
      - $DOCKERDIR/letsencrypt:/letsencrypt
      
    environment:
      - CLOUDFLARE_EMAIL=$CF_API_EMAIL
      - CLOUDFLARE_DNS_API_TOKEN=$CF_API_TOKEN
  
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`$DOMAINNAME`)'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.middlewares=strip'
      - 'traefik.http.middlewares.strip.stripprefix.prefixes=/traefik'
       # Plex
      - 'traefik.http.routers.plex.rule=Host(`plex.$DOMAINNAME`)'
      - 'traefik.http.routers.plex.entrypoints=web'
      - 'traefik.http.routers.plex.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.plex.service=api@internal'
      - 'traefik.http.services.plex.loadBalancer.server.url=http://10.0.60.100:32400'

      
    restart: unless-stopped
    
    #networks:
    #  - admin

    
