version: "3.9"

services:
  traefik:
    image: traefik:latest    
    name: traefik
    command:      
      - --api=true      
      - --global.checkNewVersion=true               
      - --log.level=DEBUG                          
      - --log.filePath=/logs/traefik.log            
      - --accessLog.filePath=/logs/access.log       
      - --accessLog.bufferingSize=100               
                                 
      - --providers.docker=true                     
      - --providers.docker.exposedbydefault=false   
      - --providers.docker.endpoint=unix:///var/run/docker.sock 

      - --entryPoints.console.address=:8080        
      - --entryPoints.web.address=:80              
      - --entrypoints.websecure.address=:443        
                  
      - --entryPoints.web.http.redirections.entryPoint.to=websecure     
      - --entryPoints.web.http.redirections.entryPoint.scheme=https     
      - --entryPoints.web.http.redirections.entrypoint.permanent=true   
                                      
      - --certificatesResolvers.letsencrypt.acme.email=$CF_API_EMAIL
      - --certificatesResolvers.letsencrypt.acme.storage=acme/acme.json        
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory     
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true 
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare 
      
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      
    volumes:
      - "/run/user/$PGID/docker.sock:/var/run/docker.sock:ro"
      - "$DOCKERDIR/letsencrypt:/letsencrypt"

    environment:
      - CF_API_EMAIL=$CF_API_EMAIL   
      - CF_API_KEY=$CP_API_KEY
  
      
    restart: always
    
