version: "3.9"

services:
  portainer:
    container_name: portainer

    image: portainer/portainer-ee:latest

    volumes:
      - /run/user/$PGID/docker.sock:/var/run/docker.sock

    ports:
      - 8000:8000
      - 9443:9443

    restart: unless-stopped

    networks:
      - admin
