version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma

    volumes:
      - $DOCKERDIR/uptime-kuma/data:/app/data
    
    restart: unless-stopped

    ports:
      - 8000:443
      
